name: pkg
description: Enhanced pub package commands to manage and interact with project dependencies.
version: 0.0.4
homepage: https://github.com/leoafarias/pkg
executables:
  pkg: pkg

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.0
  cli_util: ^0.3.0
  fvm: ^2.0.6
  io: ^1.0.0
  path: ^1.8.0
  process_run: ^0.12.1
  pub_api_client: ^2.0.4
  yaml: ^3.1.0
  yaml_edit: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  build_test: ^2.1.0
  build_version: ^2.0.2
  effective_dart: ^1.3.1
  meta: ^1.3.0
  test: ^1.17.2
  test_cov: ^1.0.1
