name: pkg
description: Enhanced pub package commands.
version: 0.0.1
homepage: https://github.com/leoafarias/pkg
executables:
  pkg: pkg

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^2.0.0
  cli_util: ^0.3.0
  io: ^0.3.5
  meta: ^1.3.0
  path: ^1.8.0
  process_run: ^0.11.2+8
  pub_api_client: ^1.0.9
  yaml_edit: ^1.0.3

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_version: ^2.0.2
  effective_dart: ^1.3.1
  test: ^1.16.5
