name: Test pkg

on: [pull_request]

jobs:
  test:
    name: "${{ matrix.sdk-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        sdk-version: [stable] #, dev]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
          - os: windows-latest
            TARGET: windows

    steps:
      - uses: actions/checkout@v1
      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: ${{ matrix.sdk-version }}

      # - name: Setup Flutter ${{ matrix.sdk-version }}
      #   uses: DanTup/gh-actions/setup-flutter@master
      #   with:
      #     channel: ${{ matrix.sdk-version }}

      - name: Install dependencies
        run: pub get

      - name: Run Test and Builder
        run: pub run build_runner test --delete-conflicting-outputs
